name: Build RSDKv5U
on:
  workflow_dispatch

jobs:
  rsdkv5u:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Download libogg and libtheora for easier includes
        run: |
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.5.zip" -OutFile "libogg.zip"
          Expand-Archive -Path libogg.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libogg-1.3.5 libogg
          Invoke-WebRequest -Uri "http://downloads.xiph.org/releases/theora/libtheora-1.2.0alpha1.zip" -OutFile "libtheora.zip"
          Expand-Archive -Path libtheora.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libtheora-1.2.0alpha1 libtheora
      - name: Download SDL2
        run: |
          Invoke-WebRequest -Uri "https://libsdl.org/release/SDL2-devel-2.28.3-VC.zip" -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/SDL2-2.28.3 SDL2
      - name: Run vcpkg
        run: |
          vcpkg install libogg:x86-windows-static-md libtheora:x86-windows-static-md
          vcpkg integrate install
      - name: Build rsdkv5u
        run: |
          msbuild RSDKv5U.sln -target:RSDKv5U-sdl2 /p:Configuration=Release /p:Platform=x86 /p:ForceImportBeforeCppTargets="$env:GITHUB_WORKSPACE/props/winactions.props"
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/Win32/Release/* ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: rsdkv5u
          path: artifacts
